apiVersion: batch/v1
kind: Job
metadata:
  name: assignmenttesting-job
spec:
  template:
    metadata:
      labels:
        app: assignmenttesting
    spec:
      containers:
        - name: assignmenttesting
          image: vaishnaveeshree03/assignmenttesting:latest
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
